### ISSUE TITLE
Potential merge issue with get_item method ?

### ISSUE THREAD

**Issue by AnBucquet** [neuropoly/medicaltorch#4]
Thanks to @andreanne-lemay, the dataset class [`MRI2DSegmentationDataset`](https://github.com/neuropoly/medicaltorch/blob/master/medicaltorch/datasets.py#L228) supports multi-channel `input`. However the [`__getitem__`](https://github.com/neuropoly/medicaltorch/blob/master/medicaltorch/datasets.py#L330) method returns a single tensor (which is the concatenation of all the input tensors) in that case. I think that might be a bit too specific to our problem and might be a problem to merge our repo with the original **MedicalTorch**. 

Would it be possible to return a list of tensors instead (even in the case of a singe channel) ? A **stack transformation** can then be applied to get the same output.

Additionally, the same philosophy might be applied to the **GT** and **ROI** as they are not necessarily identical regarding the modality (even if they should ...).

**Comment by charleygros** [comment]
The advantage that I see with your solution @AnBucquet is that it would allow to process multi-modal data either in a multi-channel way, either with CNNs in parallel (i.e. multi-path configurations: one branch processes T2w and another one, T2*w). Quite flexible!
