### ISSUE TITLE
Loader loading entire dataset in RAM causing excessive RAM usage #2

### ISSUE THREAD

**Issue by AnBucquet** [neuropoly/medicaltorch#6]
Currently, it seems that the `filter` argument in [MRI2DSegmentationDataset](https://github.com/neuropoly/medicaltorch/blob/master/medicaltorch/datasets.py#L228) doesn't  prevent the loader to load the entire dataset in RAM.

(As the filter in `self._prepare_indexes()` which is called after `self._load_filenames()`.)

I'm currently working on a solution to delete unrelevent slices after filter. 

Opened to suggestion!

**Comment by lrouhier** [comment]
Is it possible to freeze which images to load using a txt files to diminished the number of unused images?

**Comment by AnBucquet** [comment]
Indeed, it could be a solution. That would imply to create a text file for each strategy and update them when we add new data. 

Another possibility would be to create a .csv with every image, such that the slices could be used as columns ( **0**: no GT; **1** at least one pixels for example). Then we can apply a filter to this CSV to generate a list for the loader. Such file would be very convenient if we implement a loader that **read files on the fly** (cf [Issue-110](https://github.com/neuropoly/ivado-medical-imaging/issues/110))

**Comment by olix86** [comment]
On the same topic : do we really need to keep the original image in memory after cropping? We could save a lot of memory by discarding it

**Comment by AnBucquet** [comment]
Concerning the current implementation:
- `_load_filenames` is generating a list of "pointers" pointing the input images, GT and ROI.
(ex: [<medicaltorch.datasets.SegmentationPair2D object at 0x7fd91e9efac8>, <medicaltorch.datasets.SegmentationPair2D object at 0x7fd91d8b8f60>]) 
- `_prepare_indexes` will go through that list and select some specific slices using a filter. It will generate another list with the same "pointers" and the indexes of the selected slices.

Conclusion: The entire dataset is loaded, but only part of it used.

An alternative would be to merge both methods to generate a list with only the slices we want to keep. (Besides the .txt file idea is compatible with that solution)
